Change typeahead to tsx
TBS-EACPD/infobase pull request #1042
Opened 2021-04-27 17:09 UTC by GarvinH

2021-04-27 17:47 UTC, GarvinH commented on client/src/components/Typeahead/Typeahead.tsx
> +import { TypeaheadA11yStatus } from "./TypeaheadA11yStatus";
typescript doesn't like it when we use `.ts`/`.tsx` endings for imports

2021-04-27 17:49 UTC, GarvinH commented on client/tsconfig.json
> +    "target": "ES5",
without this, using the `get` accessors throws an error by the linter

2021-04-27 17:50 UTC, GarvinH commented on client/src/components/Typeahead/Typeahead.stories.js
> +import { Typeahead } from "./Typeahead.tsx";
Not sure why using `.tsx` is ok here though

2021-04-27 18:00 UTC, Stephen-ONeil requested changes
Some comments/questions

2021-04-27 18:35 UTC, GarvinH commented on client/tsconfig.json
> +    "target": "ES5",
without this, using the `get` accessors throws an error by webpack

2021-04-27 18:38 UTC, GarvinH commented on client/src/components/Typeahead/Typeahead.tsx
> +            {({ width }: any) => (
I was mainly thinking that because those values are from an external library, that we shouldn't really be creating our own interface for this

2021-04-27 18:43 UTC, GarvinH commented on client/src/components/Typeahead/Typeahead.tsx
> +  handle_up_arrow = (e: React.KeyboardEvent<HTMLInputElement>) => {
Yea i typed change event and it automatically added it haha, but yea I'll remove the `React` since it's probalby better long term

2021-04-27 19:49 UTC, GarvinH commented
Tried to change the `AutoHeightVirtualList` to become ts as well but it's kinda tricky to get it work. Gonna skip it for now

2021-05-12 18:56 UTC, AlexCLeduc commented
Typeahead has some non-typed dependencies, but I think it's probably still worth merging. We might run into some small type errors later on when its deps are typed. One may have to be manually typed, though, and that's the `any` for the function passed as `rowRenderer` to `AutoHeightVirtualList`

2021-05-12 22:57 UTC, AlexCLeduc commented on client/src/components/Typeahead/Typeahead.tsx
> +            {({ width }: any) => (
In this case, installing `@types/react-virtualized` made this function automatically recognize that `width` is a `number`

2021-05-12 22:59 UTC, merged