Implemented SpinnerWrapper component
TBS-EACPD/infobase pull request #1080
Opened 2021-05-14 15:17 UTC by csong202

Bugs:
- spinner disappears on canvas when use_leaf_spinner is switched from true to false
 need to go to docs then back to canvas to see the spinner.  
- adjusting the scale of non-leaf spinner doesn't work on canvas
 need to go to docs then back to canvas to see the effect of changing the scale.  
- box for spinner in docs is too small

2021-05-14 15:29 UTC, csong202 commented
just realized that I need multiple components for different formats and sizes

2021-05-14 17:10 UTC, ktw1016 requested changes

2021-05-14 17:10 UTC, ktw1016 commented on client/src/components/SpinnerWrapper/SpinnerWrapper.js
> +import { LeafSpinner } from "../LeafSpinner.js";
I think it's fair to rename folder name `SpinnerWrapper` to `Spinner` and include LeafSpinner all together !

2021-05-14 17:10 UTC, ktw1016 commented on client/src/components/SpinnerWrapper/SpinnerWrapper.stories.js
> +export const Basic = Template.bind({});
You should make a story for each spinner config found in `LeafSpinner.js`, `leaf_spinner_configs`!

2021-05-28 17:04 UTC, csong202 commented
Making a new branch (spinner_wrapper_story_v2) off of master and doing a pull request from there.

2021-05-28 17:04 UTC, closed without merging