fixed bug: added new config to leaf_spinner_configs
TBS-EACPD/infobase pull request #1091
Opened 2021-05-21 13:52 UTC by csong202

- Scale wasn't working because when there is no config_name the LeafSpinner used the first config (initial) in leaf_spinner_configs.
- Fixed bug by adding a new config before initial that uses default_spinner_config_form(spinner_scale)

2021-05-21 19:20 UTC, Stephen-ONeil requested changes
Can you give an example of where this occurs as a bug?

I think this may actually be more of a poorly designed API on `SpinnerWrapper`'s part than a bug with `LeafSpinner`. `SpinnerWrapper` has the (\*unused?) option to render a spinner using the non-react `spin.js` version of our spinner, which is the only case in which it uses the `scale` prop. When (default case) it's just rendering a `LeafSpinner`, the `scale` prop shouldn't have been used.

\* I don't see anywhere that the `use_leaf_spinner: true` default is overridden. Seems, in practice, this wrapper doesn't do anything. Going to guess the need for rendering a non-React spinner was some legacy case we've since moved past. Could find and replace `SpinnerWrapper` with `LeafSpinner` and delete `SpinnerWrapper` without change anythings (I think we should actually, since `SpinnerWrapper` is a weird concept with a bad API anyway :laughing:).

In the case where we just drop `SpinnerWrapper`, we could also drop the `scale` prop anywhere it was being used. I think we want things picking from a predefined set of configs rather than supplying ad hoc scale values, for consistency :+1:

2021-05-21 19:36 UTC, csong202 commented
It was more something that I noticed while messing around with the storybook controls. Yeah, that approach makes a lot more sense.

2021-06-14 20:48 UTC, Stephen-ONeil commented
@csong202 is this something you are planning to return to, or should this be closed/maybe archived as an issue?

2021-06-15 14:03 UTC, Stephen-ONeil commented
Related #1140

2021-06-15 14:03 UTC, closed without merging