More Javascript to Typescript
TBS-EACPD/infobase pull request #1122
Opened 2021-06-07 15:05 UTC by IvanFeng1

2021-06-08 00:02 UTC, IvanFeng1 commented
https://github.com/TBS-EACPD/infobase/blob/a2f36cbd3ac2e87b6b2475cb986862875ed2100a/client/src/core/ensure_loaded.ts#L426-L433

I am currently getting an error on Line 433 because `.uniqBy()` requires a parameter but the javascript code had no parameter for this function. My workaround for this locally is making  parameters not required for `.uniqBy()`  in the function definition, which is in the node_modules but I don't know how to fix this for the remote repo.

2021-06-08 18:31 UTC, Stephen-ONeil commented
The default `uniqBy` function is `_.identity` https://lodash.com/docs/4.17.15#uniqBy. That'll be the case for most lodash utils that take a predicate function. A little annoying the lodash types doesn't account for that.

2021-06-11 15:31 UTC, ktw1016 requested changes

2021-06-11 15:31 UTC, ktw1016 commented on client/src/components/LogInteractionEvents.tsx
> +  style: { display: string };
You can use `React.CSSProperties` here

2021-06-11 15:31 UTC, ktw1016 commented on client/src/components/LogInteractionEvents.tsx
> +  children: React.ReactElement;
ReactNode over ReactElement I think

2021-06-11 15:31 UTC, ktw1016 commented on client/src/components/Panel.tsx
> +interface Footnote {
I would rather you drop converting Panel.js for now for the same reason as ensure_loaded.
These footnotes, subject should be built from the ground up

2021-06-11 17:21 UTC, ktw1016 approved these changes
👍👍

2021-06-11 17:35 UTC, merged