Ts lint fixes
TBS-EACPD/infobase pull request #1160
Opened 2021-06-21 17:51 UTC by ktw1016

2021-06-22 12:29 UTC, ktw1016 commented on client/src/general_utils.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
`any` in this file for `this` keyword. Not sure how to make decorators type safe

2021-06-24 20:27 UTC, Stephen-ONeil requested changes
Pretty minor things mostly

2021-06-25 13:19 UTC, ktw1016 commented on client/src/charts/graphRegistry.ts
> +class GraphRegistry<T extends Record<string, unknown>> {
👍

2021-06-25 13:24 UTC, ktw1016 commented on client/src/components/DisplayTable/DisplayTable.tsx
> +  string | ((val: string | number | Date) => string | React.ReactNode);
Yup I absolutely should

2021-06-28 13:44 UTC, Stephen-ONeil approved these changes
:+1:

2021-06-28 14:20 UTC, merged