Convert VisibilityControl to typescript
TBS-EACPD/infobase pull request #1332
Opened 2021-12-09 03:54 UTC by sranc046

Leaving out story conversion for now since not worth the trouble if we are removing them...

2021-12-10 20:08 UTC, Stephen-ONeil requested changes

2021-12-10 20:08 UTC, Stephen-ONeil commented on client/src/components/VisibilityControl/VisibilityControl.tsx
> +  text: HTMLElement;
`icon` and `text` should be `React.ReactNode` (basically anything that is valid for the curly brackets inside of a JSX block to evaluate to; more JSX, a string, null, etc). 

Looks like the component also allows for them to be `undefined`, which the current typing doesn't accept (coincidentally, a `React.ReactNode` would) 

Maybe `text` should actually be a string, depends if the styles from `.visibility-control__text` make for a usage that should be constrained to text content.

Arguably count _could_ also be of type `React.ReactNode`, based on usage, although I think number is better. Just double check that that (and the rest of the typing) aligns with the current actual usage of this component\*.

\* important to check existing usage while typing, _but_ there's a balance to be struck between matching current usage and taking this as a chance to enforce tighter typing. Play it by ear.

2021-12-10 20:08 UTC, Stephen-ONeil commented on client/src/components/VisibilityControl/VisibilityControl.tsx
> +            [key: string]: boolean | JSX.Element | Element;
`[key: "count" | "icon" | "text"]: React.ReactNode`

If you've addressed my first comment then `"count" | "icon" | "text"` is now duplicated, so probably extract that to it's own type to DRY things out.

2021-12-10 20:08 UTC, Stephen-ONeil commented on client/src/components/VisibilityControl/VisibilityControl.tsx
> +                  (component: string) => item_components[component]
I think if the above typing is sorted out, this should be able to figure out that it's `"count" | "icon" | "text"` automatically, won't need to be told it's a string.

2021-12-13 16:39 UTC, Stephen-ONeil requested changes
Minor comments

2021-12-13 16:39 UTC, Stephen-ONeil commented on client/src/components/VisibilityControl/VisibilityControl.tsx
> +  item_component_order: ("count" | "icon" | "text")[];
Use `itemType` here

2021-12-13 16:39 UTC, Stephen-ONeil commented on client/src/components/VisibilityControl/VisibilityControl.tsx
>                <div className="visibility-control__count_area" key="count">
Can remove `key=count"` etc, given at line 107

2021-12-15 18:35 UTC, Stephen-ONeil requested changes
Sorry, didn't highlight the other cases because they're outside of the current diff range, but
> Can remove key=count" **etc**, given at line 107
that "etc" was referring to all items in `item_components`, I believe at least one other has an explicit (and no longer necessary) key.

2021-12-15 18:37 UTC, sranc046 commented
> Sorry, didn't highlight the other cases because they're outside of the current diff range, but
> 
> > Can remove key=count" **etc**, given at line 107
> 
> that "etc" was referring to all items in `item_components`, I believe at least one other has an explicit (and no longer necessary) key.

Oh my bad, completely missed that

2021-12-15 19:43 UTC, Stephen-ONeil approved these changes
:+1:

2021-12-20 18:36 UTC, merged