Cypress Axe Serious Level Issue Fixes
TBS-EACPD/infobase pull request #1364
Opened 2022-01-27 13:29 UTC by sranc046

Here are my suggested changes for our "serious" level issues. The main issues raised during the tests were related to colour contrast and nested interactive elements (regarding tooltips). After testing them out, can confirm that these issues do not break the Google Chrome screen reader or Mac VoiceOver.

- As far as I can tell, the colour contrast is a bug and only raises an issue during the tests. Does not seem to appear on the main site. Which means I haven't been able to find how to fix it. I believe it has something to do with positioning of certain elements at the time of the scan? Anyways, I suggest disabling this rule as I have already addressed the critical level version (which lead to some colour tweaking of small fonts on light backgrounds). I think this rule is "easy enough" to follow and apply without the need for a check during tests.

- Since (I think) we are dropping tooltips soon I suggest just excluding these elements from the scan. Replacements for these tooltips might be tricky if we are trying to follow this rule about interactive nested elements but at least they don't break the two screen readers mentioned above. If this problem arises again with the implementation, we always have the option of excluding them too.

Apologies for just a single commit, lots of testing back and forth around whole codebase, enabling and disabling of elements/rules, and just lost track of progress. Follow up PR for moderate level issues soon, mostly just consists of heading level semantics that are fiddly to adjust.

2022-01-27 16:12 UTC, Stephen-ONeil requested changes
Suggestions in Infographic.js should be dealt with~, comments on lack of granularity in controls for Axe can be a follow up issue/branch.~

2022-01-28 20:38 UTC, Stephen-ONeil commented
- [ ] Also fix CI build only color-contrast on `.lang-switcher` by changing how that big red dev link banner looks (I don't remember how that dev link banner works though, haha)

2022-01-28 20:48 UTC, Stephen-ONeil commented on client/cypress/integration/InfoBase/route_tests.spec.js
> +      },
Fixed with snapshot allow list

2022-01-31 16:52 UTC, sranc046 commented on client/src/infographic/Infographic.js
> +        <div ref={this.main_content}>
So the problem I was trying to resolve here was that there is an error when applying an aria-label to a div that has no content (ex: infographic/dept/326/all_data).

2022-01-31 20:01 UTC, Stephen-ONeil commented on client/src/infographic/Infographic.js
> +        <div ref={this.main_content}>
Haha, that one's a bug https://github.com/TBS-EACPD/infobase/issues/1369

2022-02-08 19:43 UTC, Stephen-ONeil approved these changes
Very minor cleanup points, please address those before merging, but pre-approved to go once you've done that :+1:

2022-02-08 19:43 UTC, Stephen-ONeil commented on .eslintignore
> +*/transpiled_build/
Minor rebase cleanup, this line was dropped on master I believe. Can delete it here too (if you have a local `transpiled_build` directory anywhere, you can delete it too)

2022-02-08 19:43 UTC, Stephen-ONeil commented on client/src/components/CheckBox/CheckBox.tsx
> +          data-cy="checkbox"
Oh, this can be cleaned up too.

2022-02-08 19:43 UTC, Stephen-ONeil commented on client/src/components/VisibilityControl/VisibilityControl.tsx
> +      <div className="visibility-control" data-cy="visibility-control">
Another unused `data-cy`

2022-02-08 20:49 UTC, merged