Replacing bootstrap 3 with 4
TBS-EACPD/infobase pull request #813
Opened 2020-11-02 19:26 UTC by GarvinH

closes #84 

related to #739 

With typeahead no longer holding us back from updating bootstrap, I've went ahead and started the process.
Immediate oddities have been fixed but I'm still searching around to see if there's any issues with the styling.

Notes:

- TreeMap no longer works
- I had to update react in order for react bootstrap to continue working
  - The lifecycle deprecation issues are now back and we're going to have to fix it

2020-11-06 21:53 UTC, Stephen-ONeil commented
Not testcafe related, prod builds are what broke. I see that, in the package lock, there were a number of babel related package changes. Those could be the culprit, have to check if we need to change our weback setup because of it (or if they might require webpack 5 or something, haha). Looks like the webpack update's a potential blocker for this. 

Also, if you run `npm install` with this `package.json` you'll see a LOT of warnings for missing/incorrect peer dependencies. None of them look like they'd be something that would cause prod builds to break while dev builds still work, but I am pretty surprised that things aren't generally far more broken with that many issues.

2020-11-06 21:58 UTC, Stephen-ONeil commented
Found some discussion of an error like this related to `uglifyjs-webpack-plugin`, supposedly fixed in 2.2.0 (we're on 2.1.1).

2020-11-06 22:01 UTC, ktw1016 commented
oh haha and uglifyjs is deprecated now😂 well I guess may as well try for it (btw I'm replacing it with Terser in my webpack branch)

2020-11-06 22:06 UTC, Stephen-ONeil commented
Can confirm that updating to `uglifyjs-webpack-plugin` 2.2.0 fixed my local prod builds at least. If you want to keep working on this branch right now then I'd suggest you do that, even if we'll be switching to terser sooner rather than later, so that the route load tests work in the mean time.

2020-11-06 22:12 UTC, ktw1016 commented
yup working, awesome👍😏

2020-11-27 18:53 UTC, GarvinH commented
waiting for typeahead

2021-02-09 14:11 UTC, GarvinH commented
I can take this back for the time being

2021-02-09 18:37 UTC, Stephen-ONeil commented
Going through, didn't see anything obvious in the standard view (🎉 ), starting to go through with mobile emulation now. Will be posting screenshots here as I go.

Glossary:
  - master
![image](https://user-images.githubusercontent.com/11301919/107410883-db9fd800-6adb-11eb-8b3c-5d279971a914.png)
  - here
![image](https://user-images.githubusercontent.com/11301919/107410928-ec504e00-6adb-11eb-828a-0475d76abc1b.png)

2021-02-09 18:41 UTC, Stephen-ONeil commented
Haha, maybe it's just the one, nothing else jumping out. Will continue a bit longer and try and check over on IE too, in a bit.

2021-02-09 18:43 UTC, Stephen-ONeil commented
- [ ] Ah, glossary tooltips are a bit off. The arrows are missing and I think the font size is smaller.

2021-02-09 18:57 UTC, Stephen-ONeil commented on client/src/InfoBase/index.hbs.html
> +            <div class="col-md-8 col-4">
Hmm, we could avoid having to re-publish these files if we re-add support for `col-xs-`, at least 4 and 8 (maybe with some big comments explaining that they're for temporary legacy index support, and shouldn't be used elsewhere).

Is removing the divs below necessary, or just cleanup? If it was necessary, could be get around it with some other specific CSS elsewhere?

2021-02-09 18:59 UTC, Stephen-ONeil commented on client/src/components/EmailFrontend.js
> +  <div className={`${form_type}`}>
Unnecessary template literal

2021-02-09 19:02 UTC, Stephen-ONeil commented on client/src/components/EmailFrontend.js
> +        style={{ marginRight: "1rem" }}
Saw you using rem's, here and elsewhere. I'd not recommend it. rem and em are good if you're careful and consistent in their use, or if they're being used for specific layouts that really should scale with font size changes. I don't think we want some obscure margins shifting around if we ever change the font on the root element though.

2021-02-09 19:06 UTC, Stephen-ONeil commented on client/src/components/EmailFrontend.js
> +  <div className={`${form_type}`}>
Unless `form_type` can possibly be undefined? I don't think the email backend allows that, but could always use the `classnames` util to be safe.

2021-02-09 19:08 UTC, Stephen-ONeil commented on client/src/components/EmailFrontend.js
> +                }`}
Replace template literal with `classnames` util, as is this is going to be setting a `className={"false"}` pretty often. OR add a `|| ""` to the end of the expression, but the `classnames` util is just a little cleaner/used more consistently than that.

2021-02-09 19:10 UTC, Stephen-ONeil commented on client/src/glossary/glossary.js
> +    <div className="col-sm-12 col-md-8 offset-md-2 font-large">
Switch to `fcol`s

2021-02-09 19:11 UTC, Stephen-ONeil commented on client/src/search/EverythingSearch.js
> +        <div className="col-md-12">
Switch to `fcol`s. I'm going to stop commenting on these if I see others, something we should try and do a general sweep for.

2021-02-09 19:11 UTC, Stephen-ONeil commented on client/src/search/EverythingSearch.js
> +        <div className="col-md-12">
Oh, hahaha, this was the last file in the diff XD

2021-02-09 19:15 UTC, Stephen-ONeil commented on client/src/InfoBase/index.hbs.html
> +            <div class="col-md-8 col-4">
If we're keeping them around, the right place to stick them would be `wet-bootstrap3-holdovers.scss`.

2021-02-09 19:20 UTC, Stephen-ONeil commented
Just a reminder that we've got a bunch of bootstrap overwrites and holdovers from the previous CSS framework WET (a fork/extended version of bootstrap some GoC folks maintain) in `src/extended_bootstrap_css`. Should check if of the classes being extended in there were deprecated or changed significantly by bootstrap 4, and wether we're even using any of them still. It might largely be stuff used by the home page at this point (in which case it should stay more or less as-is for now).

Doesn't have to be super in-depth though. Cleaning up that, and everything in `src/common_css`, is a whole kettle of fish on its own.

2021-02-09 20:05 UTC, Stephen-ONeil commented
One more general issue:
  - [ ] the spacing between the `.well`s in this panel has changed. Very minor here, but I think the RPB and maybe the graph legends also use the `.well` class, so double check that this doesn't mess more with anything else (or figure out what changed and patch it, either one)

IE 11 issues:
  - [ ] Canada flag in header is a weird size (kinda hard to see, haha, the dev link banner covers it)
  - [ ] legend content under the treemap explorer is squished
  - [ ] these IE issues appear to be problems on master too, oops
    - [ ] typeahead options dropdown is extra wide in IE. Other dropdowns (`DisplayTable` menus etc) look fine
    - [ ] typeahead results are extra tall in IE
    - [ ] legends with lots of items overflow, e.g. transfer payments expenditures panel for agriculture

2021-02-11 21:17 UTC, Stephen-ONeil commented
This comment still applies https://github.com/TBS-EACPD/infobase/pull/813#issuecomment-776155388

2021-02-11 21:55 UTC, Stephen-ONeil requested changes
Two more things, plus the glossary tooltips mentioned earlier. After that, I think we should just get one more set of eyes (@ktw1016 ?) to look over everything on the site and we might be good!

2021-02-11 21:55 UTC, Stephen-ONeil commented on client/src/components/Tombstones.js
> +        <dd className="col-10">{item}</dd>
Not handling small screens. Probably want these to be something like `md`, and to give both the label and item 12's for `sm`. Should probably be switched to `frow`/`fcol`s too?
![image](https://user-images.githubusercontent.com/11301919/107702393-2a8a7080-6c88-11eb-94ca-1a539c58b2c6.png)

There was one other `dl-horizontal` in this PR I think, apply the same fixes there.

2021-02-11 21:55 UTC, Stephen-ONeil commented on client/src/components/WellList.js
>  const WellList = ({ elements }) => (
Maybe rename to `CardList`, haha, not `well`-based anymore.

2021-02-12 16:02 UTC, ktw1016 commented
Everything looks good. I just found a minor weird margin issue on Estimates compare. Otherwise LGTM!
<img width="616" alt="Screen Shot 2021-02-12 at 10 59 29 AM" src="https://user-images.githubusercontent.com/29746626/107791266-b8666a00-6d21-11eb-85ba-85c9050792af.png">

2021-02-15 21:32 UTC, Stephen-ONeil requested changes
Found some glossary tooltips with strange placement, please investigate.
![image](https://user-images.githubusercontent.com/11301919/107994835-6cc6f100-6fab-11eb-9a1c-bfb7af9e026d.png)

2021-02-15 21:50 UTC, Stephen-ONeil requested changes
Just some other comments on new tooltip related code. Minor stuff, main thing to do is still figure out the oddly placed tool tips from the comment above.

2021-02-15 21:50 UTC, Stephen-ONeil commented on client/src/models/glossary.js
> +const glossary_display = (item) => `<div aria-live="polite">
Good idea! I believe we still replace glossary tooltips with glossary links in the text-only site, but it's worth checking if this behaves well enough that we can switch to using tooltips on the text-only version too,

2021-02-15 21:50 UTC, Stephen-ONeil commented on client/src/glossary/TooltipActivator.js
> -// The 0 second delay could still result in the _show call being stuck pending for extended periods (was consistently > 1 second on mobile Chrome)
Glad to see this stuff go! `tippy.js` seems to work fine on my mobile chrome, nice.

I'd forgot all about this hackyness. If I'd remembered I would have redone it using `patch-package`, or thought to switch tooltip libraries sooner, ha.

2021-02-15 21:50 UTC, Stephen-ONeil commented on client/package.json
> +    "@tippyjs/react": "^4.2.0",
Unused now, right? Is it a sibling dependency of `tippy.js` or something?

2021-02-15 21:50 UTC, Stephen-ONeil commented on client/src/glossary/TooltipActivator.js
> +                appendTo: body, //silence the warning
Repeat of lines 70 to 81, right? Would probably be good to DRY these, just to avoid them going out of sync when future developers make edits.

2021-02-15 21:52 UTC, Stephen-ONeil commented on client/src/glossary/TooltipActivator.js
> +                appendTo: body, //silence the warning
Ah, haha, wait. Unless I'm missing something I think they already went out-of-sync in 
b32d3a6. Or are they actually supposed to be different configurations:?

2021-02-16 16:31 UTC, Stephen-ONeil approved these changes
Couple more minor comments to address, but otherwise... approved! 🎉

2021-02-16 16:31 UTC, Stephen-ONeil commented on client/src/InfoBase/App.js
> +            {<TooltipActivator />}
Super minor, but these curly brackets aren't necessary anymore

2021-02-16 16:31 UTC, Stephen-ONeil commented on client/src/search/EverythingSearch.js
> +        <div className="col-md-12">
IS there a reason it's not an `fcol`?

2021-02-16 16:57 UTC, GarvinH commented
Yea, the `componentWillReceiveProps` function is deprecated. I'll look into the components which use it and see if I can switch it out.

The only component I know right away is that Nivo uses this function 😐

2021-02-16 17:06 UTC, Stephen-ONeil commented
Oof. We already know updating Nivo will be a whole thing (with all the undocumented API changes... and it will probably mean updating D3 at the same time, so we don't have to load two whole versions of it). If the deprecations are just warnings, that can be it's own issue/future PR.

Please check if FlipMove has a new version that's on React 17, and whether it's a quick enough upgrade to fit in to this PR.

2021-02-16 18:11 UTC, GarvinH commented
found a warning in RPB for package `react-aria-modal` which is about for `componentWillMount`.

Seems like there's an open PR for it so we're gonna have to wait a while before the warning is gone:
https://github.com/davidtheclark/react-aria-modal/pull/95

2021-02-16 18:46 UTC, merged