Infographic table contents
TBS-EACPD/infobase pull request #988
Opened 2021-04-01 16:11 UTC by GarvinH

closes #659

2021-04-06 18:49 UTC, ktw1016 requested changes
This concept is good to me, I was kinda hoping I'd somehow incorporate this functionality with panel filtering (which I'm not sure how that'd be possible) but this is more realistic solution. 
- [x] font size of "Table of contents" is inconsistent with  "Filter panels". I think they can both be the smaller size of the two
- [x] On panel filter, click on "All" or "None". It scrolls to the bottom of the page, which shouldn't happen
- [x] Table of contents panel list not updating well with panel filtering. For example, on finance infograph, click on "Transfer payments by recipient region". Table of contents show correctly 1 panel. Then click on anything else on panel filter. Table of contents not updating

2021-04-06 19:20 UTC, GarvinH commented
I'm not able to replicate the panel filter scrolling to the bottom

2021-04-06 20:47 UTC, GarvinH commented
- [ ] When all/none selected, only 9 of 10 links show

the tp_by_region loads really slow -> slow enough for the table of contents to not be able to retrieve a title

2021-04-07 14:20 UTC, AlexCLeduc commented
> I'm not able to replicate the panel filter scrolling to the bottom

If you get a panel key in the URL (e.g. by using the ToC) and then filter panels, each time you change a filter, if the panel identified by the URL exists, it will scroll to it. I think this is probably a bug with the filter not clearing the URL parameter, nothing to do with your ToC

2021-04-07 18:34 UTC, ktw1016 commented
Ah I see, cool!

2021-04-07 21:58 UTC, ktw1016 reviewed
2 minor comments, and I'm pushing a commit to showcase a different way to get the titles..

I'm not really a fan of the boilerplate code having to manage `visible_panel_title` state with `add_visible_panel_title`, having to pass that down to panel component code. I think doing it in the proposed way is cleaner, gives more control of the panel titles at the infographic level. It will definitely be more work as we'll need to change how title gets passed down for all panels but that's shouldn't be a biggie

Essentially, it's passing down the `title` at a higher level on `PanelRegistry` which then, `Infographic` can access the panel objects to access `title`. Example with 3 panels. Let me know if that makes sense, and let me know your opinions on which approach is better.

2021-04-07 21:58 UTC, ktw1016 commented
Oh, one more thing, panel-inventory route is broken

2021-04-08 18:23 UTC, GarvinH commented on client/src/infographic/Infographic.js
> +            mounted={mounted}
Whoops I was removing the internal use for testing purposes but forgot to remove it from here. thanks!

2021-04-08 21:08 UTC, AlexCLeduc commented
This is pretty cool! You can use "Table des matières"  and "Passer directement à un panneau" for the french

2021-04-09 14:03 UTC, ktw1016 approved these changes
Awesome👍 Super minor comments, otherwise good to me

2021-04-09 15:26 UTC, merged